### ISSUE TITLE
UIPageViewController 中 显示scrollview

### ISSUE THREAD

**Issue by lyt3251** [banchichen/TZScrollViewPopGesture#1]
无论如何设置 都无法滑动返回

**Comment by banchichen** [comment]
你好，请问你方便把相关代码打包发我一份吗？我调试一下....  tanzhenios@foxmail.com

**Comment by banchichen** [comment]
你好，谢谢你的代码~ 之前我没有考虑到这种情况，现在好了哈~  同时我也在Demo中加了pageController的展示案例~  pod也更新了，目前1.0.2版本~
