### ISSUE TITLE
库引入后，调用系统相机，底部按钮点击无效。

### ISSUE THREAD

**Issue by XiaoLeaf** [banchichen/TZScrollViewPopGesture#11]
您好，我在项目里引用了您的这个库。但是使用后发现，调用系统相机拍照的时候，底部按钮点击无效。将库从项目中移除后，拍照就是没有问题的，或者将+load里面的方法交换注释掉，也是可以正常使用拍照，侧滑返回也支持。不知您是否知道是什么问题呢？

**Comment by banchichen** [comment]
对比下demo哈，demo里的相机可以拍照

**Comment by XiaoLeaf** [comment]
嗯，我今天自己写了个demo，引入您的库，拍照也是没有问题的。就是放在项目里面怎么都不行。将方法交换注释就可以。想问问这样会不会有什么影响？

**Comment by banchichen** [comment]
试了一下，在我的demo中倒也能正常工作，在某些case下会不会有影响也不好说，有点久远了...

要不你试试 https://www.jianshu.com/p/8170fea174da 文章精彩评论里的方案？那个侵入性更低
