### ISSUE TITLE
某些情况下使用FDFullscreenPopGesture的fd_interactivePopDisabled跟TZScrollViewPopGesture互相影响

### ISSUE THREAD

**Issue by linsaw** [banchichen/TZScrollViewPopGesture#2]
某些业务逻辑情况下使用FDFullscreenPopGesture的fd_interactivePopDisabled = YES禁掉了页面的侧滑拉回，但是添加了大佬的TZScrollViewPopGesture之后，这些禁掉的页面又能相应边缘侧滑，这个小细节盼望大佬能修复下。

**Comment by banchichen** [comment]
你好，谢谢指出~

已发布1.0.6版本，可设置tz_interactivePopDisabled为YES禁止该页面侧滑返回~
需要你再多写一行代码哈...
