### ISSUE TITLE
+load方法导致UIImagePickercontroller代理协议失效

### ISSUE THREAD

**Issue by yujieace** [banchichen/TZScrollViewPopGesture#5]
因为是在UINavigationController的load中做了swizzling，所有包含UINavigationController的地方都受到了影响，该方法导致UIImagePickerController的代理协议无法执行。去除该库后正常，望修复，谢谢。

**Comment by banchichen** [comment]
你好，1.0.6版本已发布，已修复~

是因为我在tzPop_viewWillAppear方法里，设置了自身为导航栏的代理，而代理只能有一个，业务方设置的代理就丢了...
目前已经做了处理，0.2s后把代理还回去，目前已经正常了~ 最新的Demo里，也加入了拍照的测试案例，可以去试一下~

抱歉了~
