### ISSUE TITLE
若有视频播放，在POP动画中的时候（手指不松开），会反复调用viewWillAppear 和 viewWillDisappear

### ISSUE THREAD

**Issue by ocyisheng** [banchichen/TZScrollViewPopGesture#6]
if ([[self valueForKey:@"_isTransitioning"] boolValue]) {
        return NO;
}

这个代码 改为

 if ([self.navigationController.transitionCoordinator isAnimated] ) {
        return NO;
    }

似乎可以结决

**Comment by banchichen** [comment]
你好，谢谢指出，在刚刚发布的1.0.6版本里已经加入~

**Comment by ocyisheng** [comment]
感谢你的分享@谭真

我有三个问题问题需要说明一下

1.该方法添加的问题
 直接添加到vc的view上即可生效
[self tz_addPopGestureToView:self.view];

2.关于 self.interactivePopGestureRecognizer.enabled = YES;使系统侧滑手势生效
应该是 self.interactivePopGestureRecognizer.enabled = NO;使系统侧滑失效

原因解释请看TestVc中的warning的解释

3.关于 若有视频播放，在POP动画中的时候（手指不松开），会反复调用viewWillAppear 和 viewWillDisappear 的说明

（1）这里的原因可能不是我所提的建议，因为经我后期多次测试，更换与否并不会有更好的效果。并且这两个方法貌似获取的是同一值，不同在于一个是系统暴露的，一个是私有，使用kvc获取。。

 if ([[self valueForKey:@"_isTransitioning"] boolValue]) {
        return NO;
    }
    if ([self.navigationController.transitionCoordinator isAnimated]) {
        return NO;
    }
明显都是表明是否处于动画中的一个布尔值

（2）产生的的原因：我看到一篇简书博客，解释的原因可能是 由于pop动画与播放器之间的固有系统问题造成的，他的解决方案是自定义转场画。。   这个博客是近期才有的我忘记保存了。
                           
再次感谢@谭真，希望以后多联系，我的QQ460911751，期望和你共同进步。
------------------ 原始邮件 ------------------
发件人: "谭真";<notifications@github.com>;
发送时间: 2017年7月28日(星期五) 下午2:59
收件人: "banchichen/TZScrollViewPopGesture"<TZScrollViewPopGesture@noreply.github.com>; 
抄送: "风行使者"<460911751@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [banchichen/TZScrollViewPopGesture] 若有视频播放，在POP动画中的时候（手指不松开），会反复调用viewWillAppear 和 viewWillDisappear (#6)




Closed #6.

**Comment by banchichen** [comment]
赞👍
