### ISSUE TITLE
当前界面和上个界面的导航栏颜色不同时会出现问题

### ISSUE THREAD

**Issue by batsun666** [banchichen/TZScrollViewPopGesture#7]
如果当前界面和上个界面的导航栏颜色不同, 当手指拖住一段距离后又取消拖动而停留在当前界面时, 当前界面的导航栏颜色会变成上个界面的导航栏颜色.

**Comment by banchichen** [comment]
@batsun666 Hi，这个情况应该即使没有用这个库，也是一样吧...
可以在viewDidAppear里面再设置下导航栏颜色...
